[package]
name = "add-on"
version = "0.1.0"
authors = ["707 <707472783@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.5"  # 这里的添加在adder中不能用，两个crate引入了不同版本号的库，则会自动选低版本的